// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using beckend.Data;

#nullable disable

namespace beckend.Migrations
{
    [DbContext(typeof(BatidaPontoContext))]
    partial class BatidaPontoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("beckend.Models.Marcacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Horario")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Marcacoes");
                });

            modelBuilder.Entity("beckend.Models.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EntradaId")
                        .HasColumnType("integer");

                    b.Property<int?>("SaidaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.HasIndex("SaidaId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("beckend.Models.Registro", b =>
                {
                    b.HasOne("beckend.Models.Marcacao", "Entrada")
                        .WithMany()
                        .HasForeignKey("EntradaId");

                    b.HasOne("beckend.Models.Marcacao", "Saida")
                        .WithMany()
                        .HasForeignKey("SaidaId");

                    b.Navigation("Entrada");

                    b.Navigation("Saida");
                });
#pragma warning restore 612, 618
        }
    }
}
